"""
Setup wizard API — credential configuration for first-time setup.
GET  /api/setup/status  reports what's configured (never actual values).
POST /api/setup/save    writes .env, optionally writes google-credentials.json,
                        and restarts the systemd service.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/api/setup")

_BASE = Path(__file__).resolve().parents[2]  # /opt/miniclaw
_ENV_FILE = _BASE / "config" / ".env"
_GOOGLE_CREDS_FILE = _BASE / "config" / "google-credentials.json"


def _is_set(value: str | None) -> bool:
    """True if value is a non-empty, non-placeholder string."""
    if not value:
        return False
    lower = value.lower().strip()
    return bool(lower) and not lower.startswith("your_") and not lower.startswith("change_me")


def _read_env() -> dict[str, str]:
    if not _ENV_FILE.exists():
        return {}
    result = {}
    for line in _ENV_FILE.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" in stripped:
            k, _, v = stripped.partition("=")
            result[k.strip()] = v.strip()
    return result


@router.get("/status")
async def setup_status():
    env = _read_env()
    return {
        "configured": _is_set(env.get("TELEGRAM_BOT_TOKEN")),
        "services": {
            "telegram_calls": (
                _is_set(env.get("TELEGRAM_API_ID")) and
                _is_set(env.get("TELEGRAM_API_HASH"))
            ),
            "google_calendar": _GOOGLE_CREDS_FILE.exists(),
            "groq": _is_set(env.get("GROQ_API_KEY")),
        },
    }


class SaveRequest(BaseModel):
    telegram_bot_token: str
    esam_telegram_id: str
    webhook_url: str = ""
    telegram_api_id: str = ""
    telegram_api_hash: str = ""
    google_credentials_json: str = ""
    groq_api_key: str = ""
    restart: bool = True


@router.post("/save")
async def setup_save(body: SaveRequest):
    if not body.telegram_bot_token.strip():
        raise HTTPException(status_code=422, detail="TELEGRAM_BOT_TOKEN is required")
    if not body.esam_telegram_id.strip():
        raise HTTPException(status_code=422, detail="ESAM_TELEGRAM_ID is required")

    # Write google-credentials.json if JSON provided
    if body.google_credentials_json.strip():
        try:
            parsed = json.loads(body.google_credentials_json)
        except json.JSONDecodeError as e:
            raise HTTPException(status_code=422, detail=f"Invalid Google credentials JSON: {e}")
        _GOOGLE_CREDS_FILE.write_text(json.dumps(parsed, indent=2))

    # Build .env
    lines = [
        "# MiniClaw environment — generated by setup wizard",
        "",
        "# Telegram Bot",
        f"TELEGRAM_BOT_TOKEN={body.telegram_bot_token.strip()}",
        f"ESAM_TELEGRAM_ID={body.esam_telegram_id.strip()}",
        "",
    ]

    if body.webhook_url.strip():
        lines += [f"WEBHOOK_URL={body.webhook_url.strip()}", ""]

    lines.append("# Telegram Userbot for voice calls (get from https://my.telegram.org)")
    if body.telegram_api_id.strip() and body.telegram_api_hash.strip():
        lines += [
            f"TELEGRAM_API_ID={body.telegram_api_id.strip()}",
            f"TELEGRAM_API_HASH={body.telegram_api_hash.strip()}",
        ]
    else:
        lines += ["# TELEGRAM_API_ID=", "# TELEGRAM_API_HASH="]
    lines.append("")

    lines.append("# Google OAuth credentials path")
    if body.google_credentials_json.strip():
        lines += [f"GOOGLE_CREDENTIALS_PATH={_GOOGLE_CREDS_FILE}", ""]
    else:
        lines += ["# GOOGLE_CREDENTIALS_PATH=", ""]

    lines.append("# Groq API — fast cloud transcription (get from console.groq.com)")
    if body.groq_api_key.strip():
        lines += [f"GROQ_API_KEY={body.groq_api_key.strip()}", ""]
    else:
        lines += ["# GROQ_API_KEY=", ""]

    _ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    _ENV_FILE.write_text("\n".join(lines) + "\n")

    # Restart service
    restarted = False
    if body.restart:
        try:
            result = subprocess.run(
                ["systemctl", "restart", "miniclaw"],
                capture_output=True,
                timeout=10,
            )
            restarted = result.returncode == 0
        except Exception:
            restarted = False

    return {"saved": True, "restarted": restarted}
